color0 #42474f
color1 #ffb4ab
color2 #a5c8ff
color3 #b8c7e2
color4 #edb3f3
color5 #a5c8ff
color6 #b8c7e2
color7 #e2e2e7
color8 #8d919a
color9 #ffb4ab
color10 #a5c8ff
color11 #b8c7e2
color12 #edb3f3
color13 #a5c8ff
color14 #b8c7e2
color15 #e2e2e7

cursor                #e2e2e7
cursor_text_color     #111317
background            #111317
foreground            #e2e2e7
selection_foreground  #c3c6d1
selection_background  #42474f
active_border_color   #a5c8ff
inactive_border_color #42474f
url_color             #a5c8ff

active_tab_foreground   #00315e
active_tab_background   #a5c8ff
inactive_tab_foreground #c3c6d1
inactive_tab_background #42474f
cursor_trail_color      #c3c6d1
