color0 #40484c
color1 #ffb4ab
color2 #90cfea
color3 #b2cad6
color4 #e0b9f1
color5 #90cfea
color6 #b2cad6
color7 #e1e3e5
color8 #8a9297
color9 #ffb4ab
color10 #90cfea
color11 #b2cad6
color12 #e0b9f1
color13 #90cfea
color14 #b2cad6
color15 #e1e3e5

cursor                #e1e3e5
cursor_text_color     #111415
background            #111415
foreground            #e1e3e5
selection_foreground  #bfc8cd
selection_background  #40484c
active_border_color   #90cfea
inactive_border_color #40484c
url_color             #90cfea

active_tab_foreground   #003545
active_tab_background   #90cfea
inactive_tab_foreground #bfc8cd
inactive_tab_background #40484c
cursor_trail_color      #bfc8cd
